language: php

php:
  - '7.0'
  - '7.1'

before_script:
  - composer install --no-interaction --prefer-source --dev

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

notifications:
  email:
    - tifenn.guillas@gmail.com